// apps/web/library-mini-admin-web/src/components/AddBookForm.vue
<script setup lang="ts">
import { reactive } from 'vue'
import type { CreateBookRequest } from '@/types/library'
import type { Feedback } from '@/types/api'

defineProps<{ busy: boolean; feedback: Feedback | null }>()
const emit = defineEmits<{ submit: [payload: CreateBookRequest] }>()
const categoryOptions = [
  { value: 'literature', label: '文學' }, { value: 'science', label: '科學' }, { value: 'technology', label: '科技' },
  { value: 'history', label: '歷史' }, { value: 'art', label: '藝術' }, { value: 'philosophy', label: '哲學' },
  { value: 'business', label: '商業' }, { value: 'education', label: '教育' },
]
const form = reactive<CreateBookRequest>({ title: '', isbn: '', author: '', category: 'literature', quantity: 1, isActive: true })
function submitForm() { emit('submit', { ...form, author: form.author?.trim() || undefined }) }
</script>

<template>
  <section class="panel" data-testid="add-book-form">
    <div class="panel-header"><span class="panel-icon blue">＋</span><h2>新增書籍</h2></div>
    <form class="form-body" @submit.prevent="submitForm">
      <label>書名 <span>*</span><input data-testid="add-book-title" v-model="form.title" required placeholder="請輸入書名" /></label>
      <label>ISBN <span>*</span><input data-testid="add-book-isbn" v-model="form.isbn" required placeholder="請輸入 ISBN" /></label>
      <label>作者（可選）<input data-testid="add-book-author" v-model="form.author" placeholder="請輸入作者" /></label>
      <label>分類 <span>*</span><select data-testid="add-book-category" v-model="form.category"><option v-for="option in categoryOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label>
      <label>數量 <span>*</span><input data-testid="add-book-quantity" v-model.number="form.quantity" type="number" min="1" required /></label>
      <div class="toggle-row"><div><strong>上架狀態</strong><small>書籍是否可供借閱</small></div><button data-testid="add-book-active" type="button" class="switch" :class="{ on: form.isActive }" role="switch" :aria-checked="form.isActive" @click="form.isActive = !form.isActive"><span /></button></div>
      <p v-if="feedback" data-testid="add-book-result" class="feedback" :class="feedback.type">{{ feedback.message }}</p>
      <button data-testid="add-book-submit" class="primary-button blue-button" type="submit" :disabled="busy">新增書籍</button>
    </form>
  </section>
</template>

// docs/figma/library-mini-admin-console/src/app/components/AddBookForm.tsx
import { useState } from 'react';
import { BookPlus, CheckCircle2, AlertCircle } from 'lucide-react';

type AddBookFormProps = {
  onAddBook: (data: {
    title: string;
    isbn: string;
    author?: string;
    category: string;
    quantity: number;
    isActive: boolean;
  }) => void;
  status?: { type: 'success' | 'error'; message: string } | null;
};

export function AddBookForm({ onAddBook, status }: AddBookFormProps) {
  const [formData, setFormData] = useState({
    title: '',
    isbn: '',
    author: '',
    category: 'literature',
    quantity: 1,
    isActive: true,
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (formData.title && formData.isbn) {
      onAddBook({
        title: formData.title,
        isbn: formData.isbn,
        author: formData.author || undefined,
        category: formData.category,
        quantity: formData.quantity,
        isActive: formData.isActive,
      });
    }
  };

  return (
    <div className="rounded-lg border bg-white shadow-sm">
      <div className="border-b px-6 py-4">
        <div className="flex items-center gap-2">
          <BookPlus className="h-5 w-5 text-indigo-600" />
          <h2 className="font-semibold text-gray-900">新增書籍</h2>
        </div>
      </div>

      <div className="p-6">
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              書名 <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              value={formData.title}
              onChange={(e) => setFormData({ ...formData, title: e.target.value })}
              placeholder="請輸入書名"
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              ISBN <span className="text-red-500">*</span>
            </label>
            <input
              type="text"
              value={formData.isbn}
              onChange={(e) => setFormData({ ...formData, isbn: e.target.value })}
              placeholder="請輸入 ISBN"
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"
              required
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              作者（可選）
            </label>
            <input
              type="text"
              value={formData.author}
              onChange={(e) => setFormData({ ...formData, author: e.target.value })}
              placeholder="請輸入作者"
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              分類 <span className="text-red-500">*</span>
            </label>
            <select
              value={formData.category}
              onChange={(e) => setFormData({ ...formData, category: e.target.value })}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"
            >
              <option value="literature">文學</option>
              <option value="science">科學</option>
              <option value="technology">科技</option>
              <option value="history">歷史</option>
              <option value="art">藝術</option>
              <option value="philosophy">哲學</option>
              <option value="business">商業</option>
              <option value="education">教育</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-1">
              數量 <span className="text-red-500">*</span>
            </label>
            <input
              type="number"
              min="1"
              value={formData.quantity}
              onChange={(e) => setFormData({ ...formData, quantity: parseInt(e.target.value) || 1 })}
              className="w-full rounded-md border border-gray-300 px-3 py-2 text-sm outline-none transition-colors focus:border-indigo-500 focus:ring-2 focus:ring-indigo-100"
              required
            />
          </div>

          <div className="flex items-center justify-between rounded-md border border-gray-200 bg-gray-50 px-4 py-3">
            <div>
              <label htmlFor="isActive" className="text-sm font-medium text-gray-700">
                上架狀態
              </label>
              <p className="text-xs text-gray-500">書籍是否可供借閱</p>
            </div>
            <button
              type="button"
              id="isActive"
              role="switch"
              aria-checked={formData.isActive}
              onClick={() => setFormData({ ...formData, isActive: !formData.isActive })}
              className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                formData.isActive ? 'bg-indigo-600' : 'bg-gray-300'
              }`}
            >
              <span
                className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                  formData.isActive ? 'translate-x-6' : 'translate-x-1'
                }`}
              />
            </button>
          </div>

          {status && (
            <div
              className={`flex items-start gap-2 rounded-md p-3 text-sm ${
                status.type === 'success'
                  ? 'bg-green-50 text-green-800'
                  : 'bg-red-50 text-red-800'
              }`}
            >
              {status.type === 'success' ? (
                <CheckCircle2 className="h-4 w-4 mt-0.5 flex-shrink-0" />
              ) : (
                <AlertCircle className="h-4 w-4 mt-0.5 flex-shrink-0" />
              )}
              <span>{status.message}</span>
            </div>
          )}

          <button
            type="submit"
            className="w-full rounded-md bg-indigo-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2"
          >
            新增書籍
          </button>
        </form>
      </div>
    </div>
  );
}
