// docs/figma-make/library-mini-admin-console/src/app/components/TopBar.tsx
import { Search, User } from 'lucide-react';

export function TopBar() {
  return (
    <header className="border-b bg-white">
      <div className="flex items-center justify-between px-6 py-4">
        {/* Logo */}
        <div className="flex items-center gap-2">
          <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-br from-blue-600 to-blue-700 text-white">
            <svg
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
            </svg>
          </div>
          <div>
            <h1 className="font-semibold text-gray-900">Library Mini Admin</h1>
            <p className="text-xs text-gray-500">管理控制台</p>
          </div>
        </div>

        {/* Global Search */}
        <div className="flex-1 max-w-2xl mx-12">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-gray-400" />
            <input
              type="text"
              placeholder="搜尋書名、ISBN、作者..."
              className="w-full rounded-lg border border-gray-200 bg-gray-50 py-2 pl-10 pr-4 text-sm outline-none transition-colors focus:border-blue-500 focus:bg-white"
            />
          </div>
        </div>

        {/* Admin Area */}
        <div className="flex items-center gap-3">
          <div className="text-right">
            <p className="text-sm font-medium text-gray-900">Admin</p>
            <p className="text-xs text-gray-500">管理員</p>
          </div>
          <div className="flex h-10 w-10 items-center justify-center rounded-full bg-gradient-to-br from-purple-600 to-pink-600 text-white">
            <User className="h-5 w-5" />
          </div>
        </div>
      </div>
    </header>
  );
}

// apps/web/library-mini-admin-web/src/components/TopBar.vue
<template>
  <header class="topbar" data-testid="topbar">
    <div class="topbar__brand">
      <div class="brand-mark" aria-hidden="true">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
          <path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1 0-5H20" />
          <path d="M8 6h8M8 10h8" />
        </svg>
      </div>
      <div>
        <p class="brand-title">Library Mini Admin</p>
        <p class="brand-subtitle">管理控制台</p>
      </div>
    </div>

    <div class="topbar__search">
      <label class="sr-only" for="catalogue-search">搜尋館藏</label>
      <span class="search-icon" aria-hidden="true">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <circle cx="11" cy="11" r="7" />
          <path d="m20 20-4-4" />
        </svg>
      </span>
      <input
        id="catalogue-search"
        data-testid="topbar-search"
        type="search"
        placeholder="搜尋書名、ISBN、作者..."
        aria-label="搜尋書名、ISBN、作者"
      />
    </div>

    <div class="topbar__admin" data-testid="admin-identity">
      <div class="admin-copy">
        <p>Admin</p>
        <span>管理員</span>
      </div>
      <div class="admin-avatar" aria-hidden="true">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8">
          <circle cx="12" cy="8" r="3.5" />
          <path d="M5 20a7 7 0 0 1 14 0" />
        </svg>
      </div>
    </div>
  </header>
</template>
